"""Application Settings"""

import os
from dotenv import load_dotenv

load_dotenv()

ADMIN_EMAIL = os.getenv("ADMIN_EMAIL")
ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD")
USER_EMAIL = os.getenv("USER_EMAIL")
USER_PASSWORD = os.getenv("USER_PASSWORD")

WRONG_EMAIL = os.getenv("WRONG_EMAIL")
WRONG_PASSWORD = os.getenv("WRONG_PASSWORD")

REGISTRATION_USER_USERNAME = os.getenv("REGISTRATION_USER_USERNAME")
REGISTRATION_USER_EMAIL = os.getenv("REGISTRATION_USER_EMAIL")
REGISTRATION_USER_PASSWORD = os.getenv("REGISTRATION_USER_PASSWORD")
REGISTRATION_USER_PHONE = os.getenv("REGISTRATION_USER_PHONE")

INVALID_EMAIL = os.getenv("INVALID_EMAIL")
INVALID_PASSWORD = os.getenv("INVALID_PASSWORD")
DIFFERENT_CONFIRM_PASSWORD = os.getenv("DIFFERENT_CONFIRM_PASSWORD")
