HOMEPAGE_URL = "https://quiz.itech-theme.com"
LOGIN_URL = "https://quiz.itech-theme.com/signin"
REGISTRATION_URL = "https://quiz.itech-theme.com/signup"
ADMIN_DASHBOARD = "https://quiz.itech-theme.com/admin"
USER_DASHBOARD = "https://quiz.itech-theme.com/home"
